# Generated by Django 4.2.4 on 2023-09-03 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.CharField(choices=[('SAO PAULO', 'são paulo'), ('PALMEIRAS', 'palmeiras'), ('FLAMENGO', 'flamengo'), ('SANTOS', 'santos'), ('SANTA CRUZ', 'santa cruz'), ('BOTAFOGO', 'botafogo'), ('FLUMINENSE', 'fluminense'), ('VASCO', 'vasco'), ('SPORT', 'sport')], max_length=50)),
                ('gols', models.IntegerField()),
                ('jogador', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='tournamentapp.nome')),
            ],
        ),
    ]
